### PR TITLE
First draft: Quadratic Eqn and Pythogrean theorem (C++ & Julia)

### PR DESCRIPTION
**Pull request by caseykneale**
If anyone could give this a read over and look for rambling, bad explanations, code improvements, etc, I'd really appreciate it. I did this super quickly.

### CODE REVIEW

**Comment by caseykneale** [comment]
Rendered version: https://github.com/JeffreySarnoff/ComparisonsWithJulia/blob/e60cce3dbdffd1f0acaee299bd73f94ca7ea1399/C%2B%2B/caseykneale/README.md

**Comment by JeffreySarnoff** [comment]
does the pythagorean theorem really get used with nonreal numbers?
is the negative length a result that has applicability?
```
±(x::Real) = let absx=abs(x)
     (absx, -absx)
end

pythagorean_theorem( a::Real, b::Real) = ±√(a^2 + b^2)
```

**Comment by caseykneale** [comment]
Good point. 

Question for you. Should the C++ code be similar in function to the Julia code or should it be idiomatic? There's a weird thought loop for this example.

Instead of using an array of doubles, for C++ it's more idiomatic to use a struct with 2 doubles in it. Fine. but then, Julia can be structured that way as well. But when you'd go to do that in Julia you might say "well shouldn't I just use a tuple? maybe a list? don't need a type for a collection of two floats..."

**Comment by JeffreySarnoff** [comment]
the sources should be intent equivalent, that they vary in specifics is
part of the message. Each is best doing as it best does.

**Comment by JeffreySarnoff** [comment]
revision by Will Pazner
```
using namespace std;
template <typename T> using res = array<T,2>;
template <typename T> res<T> plusMinus(T a,T b) { return {a+b,a-b}; }
template <typename T> res<T> plusMinus(T a) { return {a,-a}; }
template <typename T> auto pythagoreanTheorem(T b, T c) -> res<decltype(sqrt(b))> {
   return plusMinus(sqrt(b*b + c*c));
}
template <typename T> auto quadraticEquation(T a, T b, T c) -> res<decltype(sqrt(b))> {
    auto result = plusMinus(decltype(sqrt(b))(-b), sqrt(b*b - 4*a*c) );
    for (auto &x : result) { x /= 2*a; }
    return result;
}
```
improvement to revision by Will Pazner
```
using namespace std;
template <typename T> using res = array<T,2>;
template <typename T> res<T> plusMinus(T a,T b) { return {a+b,a-b}; }
template <typename T> res<T> plusMinus(T a) { return {a,-a}; }

template <typename T> res<T> pythagoreanTheorem(T b, T c) { 
    return plusMinus(sqrt(b*b + c*c)); 
}

template <typename T> auto quadraticEquation(T a, T b, T c) -> res<decltype(sqrt(b))> {
    auto result = plusMinus(decltype(sqrt(b))(-b), sqrt(b*b - 4*a*c) );
    for (auto &x : result) { x /= 2*a; }
    return result;
}
```

**Comment by caseykneale** [comment]
Yea I think after seeing what happens when you leave C++ and go to C++11 most of my dialog is dead. We were never allowed to use it at my one job so I never touched it, but maybe peoples views have shifted or will shift. 

So I'll redact this submission and say, I need to learn C++11

**Pull request closed without merging**
